language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install -r requirements/develop.txt
    - pip install coveralls
    - python setup.py develop
script:
  - pycodestyle --show-source --show-pep8 pyknow
  - cd docs/
  - sphinx-build -W -b html -d /tmp/doctress . /tmp/html
  - cd ..
  - coverage erase
  - coverage run -p --branch $(which py.test) -m 'not wip' -v tests/unit
after_success:
  - coverage combine
  - coverage report
  - coveralls
